<p><a id="button" href="?item=foo">Click here</a> to interact with you're basket</p>
<script type="text/javascript">
$(document).ready(function() {
    $('body').on('click', '#button', function(e) {
        e.preventDefault();
        $.ajax({
            url: '',
            method: 'post',
            data: {
                dispatch: 'basket',
                item: 'foo'
            },
            success: function (response) {
                $('[data-container="basket"]').html(response);
            }
        });
    });
});
</script>